### ISSUE TITLE
Bios folder inaccessible 

### ISSUE THREAD

**Issue by HenryAvery** [cbepx-me/RG35xx-P-RG35xx-H-Modification#1]
Seems like the default Bios folder is on the linuxroot partition. Any way to access the Bios folder or how would I add more Bios files for things like Dreamcast.

**Comment by TrilIiard** [comment]
You can access it using a Windows PC and Minipartitiontool making the Partition visible. Would be great if we could access all partitions without the need for a windows PC and minipartitiontool, just like Stock already is.

**Comment by cbepx-me** [comment]
The new modification system has added SSH support, which allows for accessing and copying BIOS files
