### ISSUE TITLE
Menu & Core Select overlap 

### ISSUE THREAD

**Issue by Saganaki22** [cbepx-me/RG35xx-P-RG35xx-H-Modification#11]
![IMG_20240409_040041_847](https://github.com/cbepx-me/RG35xx-P-RG35xx-H-Modification/assets/84208527/5d0637e1-7800-47cd-9e9f-30d9849ddc73)

When in RA Game select screen
the Menu button and Select Core Buttons and texts are overlayed making it difficult to read and see the buttons for each.

**Comment by cbepx-me** [comment]
The latest image has fixed this issue

**Comment by Saganaki22** [comment]
> The latest image has fixed this issue

we really appreciate your work, thank you!
