### ISSUE TITLE
File manager stuck on black screen (RG35XX Plus on latest firmware version)

### ISSUE THREAD

**Issue by aarontanx** [cbepx-me/RG35xx-P-RG35xx-H-Modification#12]
FW Version 2240404

**Comment by Gabi-90** [comment]
same here

**Comment by LeeNX** [comment]
Had the blank screen for what I did not understand at first, but is this not the ntp service syncing up and then the screensaver blanking the screen? I find that if I quick press the power button, it comes back on. Normally seems to be around a minute before going blank.

**Comment by Gabi-90** [comment]
Hi cbepx-me! i created this video so you can see the error better:
https://youtube.com/shorts/8OYZnCE3uL8
Thanks for your, it's excellent!

**Comment by ahmed2m** [comment]
This was the case for me before 2.0 but after 2.0 I can open the file manager

**Comment by Gabi-90** [comment]
I also use version 2.0 (the latest from cbepx-me) but this error does not occur when starting the console, it occurs after using it for a while and when I go to open the file manager it sometimes remains with a black screen and This forces me to press reset on the console.

**Comment by cbepx-me** [comment]
I have communicated with anbernic and this problem will be solved in future official updates.
