### ISSUE TITLE
SSH change default port

### ISSUE THREAD

**Issue by wtfatty** [cbepx-me/RG35xx-P-RG35xx-H-Modification#16]
I can't connect using SSH, I suspect my router is blocking the default 22 port. So I was wondering is it possible to change the default port?
I tried to uncomment and change 
`#Port 22`
in /etc/ssh/sshd_config but it doesn't seem to work. 
Thank you.

**Comment by cbepx-me** [comment]
The previous operations are correct. Finally, you need to restart the ssh service. You can do this through SSH_Server-OFF and SSH_Server-ON in APPS.
