### ISSUE TITLE
Game mode cannot be started

### ISSUE THREAD

**Issue by DanielFergisz** [cbepx-me/RG35xx-P-RG35xx-H-Modification#2]
How to run/install game mode? (retroarch/settings/power management/game mode)

Is it possible to add new platforms/edit the RA Game list?

**Comment by cbepx-me** [comment]
1. Perhaps you can find the answer here : 
FeralInteractive/gamemode: Optimise Linux system performance on demand
https://github.com/FeralInteractive/gamemode
2. I don't understand your idea. Do you want to run retroarch without the front-end of stock OS?

**Comment by DanielFergisz** [comment]
1. I was thinking about adding this option in subsequent versions of the software, I don't know Linux well ;)

2. I mean something else, I would like to add several other platforms to the list, currently, after creating a folder and adding games, it is not possible to run games from the Menu, e.g.:
- Amiga
- AmigaCD
- ZX Spectrum
etc.

![RG35xx Plus](https://github.com/cbepx-me/RG35xx-P-RG35xx-H-Modification/assets/33960601/ad708578-9646-4c4e-8891-650078a6e7e3)

**Comment by cbepx-me** [comment]
The simulator type information in the stock os is written into the front-end file and does not provide a custom addition function. Currently, this idea cannot be implemented

**Comment by DanielFergisz** [comment]
Ok, thanks for the info
