### ISSUE TITLE
Can't start game in Port master

### ISSUE THREAD

**Issue by pkoko** [cbepx-me/RG35xx-P-RG35xx-H-Modification#20]
Download the game in portmaster like https://portmaster.games/detail.html?name=2048, extract and put it in the path /roms/ports. and the system can recognise the game in RA platform. but when starts the game and it show "exiting" like immediately. Like all download game has the same issue except the stork port game in the rom

**Comment by herbix** [comment]
Port master games require files from port master. It can't be run without port master installed.

**Comment by cbepx-me** [comment]
stock os does not support this project, please wait for the new version of knulli or muos

**Comment by mahdiyari** [comment]
Can I ask what PORTS are supported? Like what ports? Are there any examples? I also thought ports meant like ports from port master.
