### ISSUE TITLE
Are you interested in updating the system and making netplay playable?

### ISSUE THREAD

**Issue by Serginhogamesbr** [cbepx-me/RG35xx-P-RG35xx-H-Modification#23]
My biggest interest in this modified rom would be to see the online netplay system working correctly, could you update retroarch? because the original stock version comes with retroarch outdated in 1.10 if it was with retroarch 1.17 or 1.18 it would be possible to play online with other people it would be great to see this working one day

**Comment by cbepx-me** [comment]
I have communicated with anbernic, they are actively trying, I believe it will come
