### ISSUE TITLE
Save folder path

### ISSUE THREAD

**Issue by thiagojeffery** [cbepx-me/RG35xx-P-RG35xx-H-Modification#53]
I use two sdcards. The second have all the roms and saves. But after the last version, v2.5, the save doesn't load anymore.

**Comment by Skeeve** [comment]
That's stock OS's fault

See here: https://www.reddit.com/r/RG35XX/comments/1dogcot/saves_stock_os_mod_rg35xxh/

**Comment by thiagojeffery** [comment]
Thanks for the info.
