### ISSUE TITLE
Rumble doesn't work

### ISSUE THREAD

**Issue by murilosys** [cbepx-me/RG35xx-P-RG35xx-H-Modification#59]
The Rumble pak feature doesn't work

**Comment by Skeeve** [comment]
Interesting.

Would you mind explaining how one can reproduce the issue you found?

**Comment by murilosys** [comment]
> Interesting.
> 
> Would you mind explaining how one can reproduce the issue you found?

Hi Skeeve, 

By playing any N64 game that support this feature we can notice that the vibration doesn't work.

**Comment by Skeeve** [comment]
Does it work without the mod?

**Comment by murilosys** [comment]
> Does it work without the mod?

It need to be tested

**Comment by Skeeve** [comment]
> > Does it work without the mod?
> 
> It need to be tested

I agree. Go ahead… Tell us the result.

**Comment by murilosys** [comment]
Also fail

**Comment by Skeeve** [comment]
So you should close this ticket and conplain to Anbernic, I guess, as it is not the Mod's fault.
