### ISSUE TITLE
Port games not working stock mod 20240626

### ISSUE THREAD

**Issue by jafar-it** [cbepx-me/RG35xx-P-RG35xx-H-Modification#66]
I downloaded 3 port game from your shared screen. I extracted and copied game folder content into PORTS folder on an external sd card. The game turns on and then exists Immediately.  Can I see logs somewhere?  What could be the issue?

**Comment by dezign999** [comment]
This fixed it for me, first download: https://github.com/PortsMaster/PortMaster-Hosting/releases/download/large-files/mono-6.12.0.122-aarch64.squashfs and then create a folder in your Ports folder called portmaster and inside of that, libs. Drop the file you downloaded into the libs folder and it should work just fine after 30+ seconds after launching.

**Comment by Hoainamtruong93** [comment]
Hello. I had already create a folder name "portmaster" in Posts folder and put the downloaded file to "libs" too, but I still could not run the port game, it is quit immediately. How can it be fixed by which way ? kindly help me

**Comment by dezign999** [comment]
Is there anything inside of your Gamedata folder? You need the steam files for this to work.

**Comment by Hoainamtruong93** [comment]
Yes. I ensure download and decompress the file port game then put entire them to the Port folder. 

Ports/Imgs
Port/tmntsr
Porrt/TMNTSR.sh
Ports/portmaster/libs/mono-6.12.0.122-aarch64.squashfs

Are there any wrong when i put it in the Ports folder ? please help to point me.

**Comment by dezign999** [comment]
There is a gamedata folder inside of the tmntsr folder. That is where all of the game files reside. If your game data folder is empty or only has a few files in it, it won’t work. The port that was posted on the Google drive does not include the game files, only the postmaster files that enable the game to run on the handheld.

**Comment by Hoainamtruong93** [comment]
Could you please instruct me to download the postmaster file to run the game. or which website can me got it ?

**Comment by jafar-it** [comment]
I got the Resolution.  I was the impression that the file provided is complete data.  Instead, we are supposed to procure the game and add it to the game data folder.  Some games worked but some still cannot. I haven't able to make TMNT work yet.  Sonic CD is working fine with some other games.

**Comment by jafar-it** [comment]
Working now.

**Comment by mahdiyari** [comment]
@dezign999 @jafar-it Where do you get the `TMNTSR.sh` file and the `tmnstr` folder?.
