### ISSUE TITLE
please provide a mirror other than Mega.nz for 64-bit images

### ISSUE THREAD

**Issue by fmpallini** [cbepx-me/RG35xx-P-RG35xx-H-Modification#67]
Can't download 2.6 version based on 1.1.4 with Mega.nz free tier.

**Comment by Skeeve** [comment]
Go tell it to anbernic. You're wrong here.

**Comment by fmpallini** [comment]
You are wrong dear friend. Stock mod 2.6 64bits was release here only on mega.nz, and after 1gb of transfer I was getting quote exceeded limit. This issue would affect anyone who doesn't have a mega paid account. 

Anyway, this issue is resolved since 2.7 was made avaliable at Google drive, I already download and installed, thanks!

**Comment by fmpallini** [comment]
Closing

**Comment by Skeeve** [comment]
Ah! I see. Read your issue wrong.
