### ISSUE TITLE
stuck on welcome screen

### ISSUE THREAD

**Issue by Mikosz06** [cbepx-me/RG35xx-P-RG35xx-H-Modification#72]
So i tried to install the newest version (2.7) on anbernic rg40xxh and it is stuck on the welcome screen for an 2 houres. I'm using branded sd card

**Comment by DanielFergisz** [comment]
mam ten sam problem na RG35XX H na mod i org software (64GB and 128GB card)

**Comment by dariocarbone** [comment]
Same here, but this issue is a replica of #70, maybe it's better to close this duplicate and continue writing there...

**Comment by jafar-it** [comment]
Same here.  There are issues already created for this problem.

**Comment by jafar-it** [comment]
Is this isssue fixed for you?

**Comment by Mikosz06** [comment]
No
