### ISSUE TITLE
Copy apps to TF2 is exists

### ISSUE THREAD

**Issue by tstrul1** [cbepx-me/RG35xx-P-RG35xx-H-Modification#8]
Currently, apps are being copied to TF1 and even without roms im asked to choose card when entering RA.
Is it possible to use TF2 for that / disable the apps recreation at boot?

Thank you

**Comment by cbepx-me** [comment]
I will consider the possibility of doing so

**Comment by cbepx-me** [comment]
Confirmed to add this feature in the next version
